required field error fixed
BlueBaseJS/plugin-json-schema-components pull request #39
Opened 2019-09-18 11:17 UTC by adnan1naeem

required field error fixed

2019-09-19 05:17 UTC, adnan1naeem commented
@artalat  please merge

2019-09-19 06:16 UTC, artalat commented
This is not the correct fix. Please discuss with me today.

2019-09-19 12:04 UTC, artalat requested changes

2019-09-19 12:04 UTC, artalat commented on src/JsonGraphqlForm/__tests__/JsonGraphqlForm.graphql.test.tsx
> -			expect(firstName.prop('helperText')).toBe('I m sorry, but we dont like your name.');
why was this test removed?

2019-09-19 12:04 UTC, artalat commented on src/JsonGraphqlForm/__tests__/JsonGraphqlForm.graphql.test.tsx
> +			expect(firstName.prop('error')).toBe(undefined);;
why was this change made?

2019-09-19 12:04 UTC, artalat commented on src/JsonGraphqlForm/__tests__/JsonGraphqlForm.graphql.test.tsx
> -			expect(password.prop('helperText')).toBe('The password cannot be less than 8 characters');
why was this test removed?

2019-09-19 12:04 UTC, artalat commented on src/JsonForm/Fields/FormTextInput.tsx
> +FormTextInput.defaultStyles = (_theme: Theme) => ({
what is the purpose of this?

2019-09-19 12:04 UTC, artalat commented on src/JsonForm/Fields/FormTextInput.tsx
> +	return (
revert to previous code style that doesnt have a return statement

2019-09-19 12:04 UTC, artalat commented on src/JsonForm/Fields/FormTextInput.tsx
> +export interface FormTextInputStyles {
why do we need this?

2019-09-19 12:04 UTC, artalat commented on src/JsonForm/Fields/FormTextInput.tsx
> +	styles?: FormTextInputStyles;
why do we need this?

2019-09-19 12:04 UTC, artalat commented on src/JsonForm/BaseFormField.tsx
> +						<MainComponent   {...props}>
why was this change made?

2019-09-20 10:56 UTC, adnan1naeem commented on src/JsonGraphqlForm/__tests__/JsonGraphqlForm.graphql.test.tsx
> -			expect(password.prop('helperText')).toBe('The password cannot be less than 8 characters');
i have reverted the code

2019-09-20 10:57 UTC, adnan1naeem commented on src/JsonGraphqlForm/__tests__/JsonGraphqlForm.graphql.test.tsx
> +			expect(firstName.prop('error')).toBe(undefined);;
I have fixed it

2019-09-20 10:57 UTC, adnan1naeem commented on src/JsonGraphqlForm/__tests__/JsonGraphqlForm.graphql.test.tsx
> -			expect(firstName.prop('helperText')).toBe('I m sorry, but we dont like your name.');
i ahev reverted the code

2019-09-20 10:58 UTC, adnan1naeem commented on src/JsonForm/Fields/FormTextInput.tsx
> +	styles?: FormTextInputStyles;
I have reverted the code

2019-09-20 11:00 UTC, adnan1naeem commented on src/JsonForm/Fields/FormTextInput.tsx
> +export interface FormTextInputStyles {
i have reverted the code

2019-09-20 11:01 UTC, adnan1naeem commented on src/JsonForm/BaseFormField.tsx
> +						<MainComponent   {...props}>
i have reverted the code

2019-09-20 11:01 UTC, adnan1naeem commented on src/JsonForm/Fields/FormTextInput.tsx
> +FormTextInput.defaultStyles = (_theme: Theme) => ({
I have reverted the code

2019-09-21 07:21 UTC, artalat requested changes

2019-09-21 07:21 UTC, artalat commented on src/JsonForm/Fields/FormTextInput.tsx
> +				error: form.errors[name] ? true : false || props.error,
```suggestion
				error: !!form.errors[name] || props.error,
```

Can you test this instead

2019-09-23 05:25 UTC, adnan1naeem commented on src/JsonForm/Fields/FormTextInput.tsx
> +				error: form.errors[name] ? true : false || props.error,
it worked fixed it

2019-09-23 06:06 UTC, artalat approved these changes

2019-09-23 08:34 UTC, artalat approved these changes

2019-09-23 08:35 UTC, merged

2019-09-23 09:52 UTC, artalat commented
:tada: This PR is included in version 2.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@bluebase/plugin-json-schema-components)
- [GitHub release](https://github.com/BlueBaseJS/plugin-json-schema-components/releases/tag/v2.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: